//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSRemoting_ConsoleProxy.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PSRequest", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class PSRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string commandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pinCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string remotePathField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string command {
            get {
                return this.commandField;
            }
            set {
                if ((object.ReferenceEquals(this.commandField, value) != true)) {
                    this.commandField = value;
                    this.RaisePropertyChanged("command");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int pinCode {
            get {
                return this.pinCodeField;
            }
            set {
                if ((this.pinCodeField.Equals(value) != true)) {
                    this.pinCodeField = value;
                    this.RaisePropertyChanged("pinCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string remotePath {
            get {
                return this.remotePathField;
            }
            set {
                if ((object.ReferenceEquals(this.remotePathField, value) != true)) {
                    this.remotePathField = value;
                    this.RaisePropertyChanged("remotePath");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PSResponse", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class PSResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string psResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int statusCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string psResult {
            get {
                return this.psResultField;
            }
            set {
                if ((object.ReferenceEquals(this.psResultField, value) != true)) {
                    this.psResultField = value;
                    this.RaisePropertyChanged("psResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                if ((this.statusCodeField.Equals(value) != true)) {
                    this.statusCodeField = value;
                    this.RaisePropertyChanged("statusCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Service", ConfigurationName="ServiceReference1.IPSRemoting")]
    public interface IPSRemoting {
        
        [System.ServiceModel.OperationContractAttribute(Action="Service/IPSRemoting/invokeCommand", ReplyAction="Service/IPSRemoting/invokeCommandResponse")]
        PSRemoting_ConsoleProxy.ServiceReference1.PSResponse invokeCommand(PSRemoting_ConsoleProxy.ServiceReference1.PSRequest datainput);
        
        [System.ServiceModel.OperationContractAttribute(Action="Service/IPSRemoting/invokeCommand", ReplyAction="Service/IPSRemoting/invokeCommandResponse")]
        System.Threading.Tasks.Task<PSRemoting_ConsoleProxy.ServiceReference1.PSResponse> invokeCommandAsync(PSRemoting_ConsoleProxy.ServiceReference1.PSRequest datainput);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPSRemotingChannel : PSRemoting_ConsoleProxy.ServiceReference1.IPSRemoting, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PSRemotingClient : System.ServiceModel.ClientBase<PSRemoting_ConsoleProxy.ServiceReference1.IPSRemoting>, PSRemoting_ConsoleProxy.ServiceReference1.IPSRemoting {
        
        public PSRemotingClient() {
        }
        
        public PSRemotingClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PSRemotingClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PSRemotingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PSRemotingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PSRemoting_ConsoleProxy.ServiceReference1.PSResponse invokeCommand(PSRemoting_ConsoleProxy.ServiceReference1.PSRequest datainput) {
            return base.Channel.invokeCommand(datainput);
        }
        
        public System.Threading.Tasks.Task<PSRemoting_ConsoleProxy.ServiceReference1.PSResponse> invokeCommandAsync(PSRemoting_ConsoleProxy.ServiceReference1.PSRequest datainput) {
            return base.Channel.invokeCommandAsync(datainput);
        }
    }
}
